apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-controller-manager
    image: {{ REGISTRY_LOCAL }}{{ K8S_IMAGES['KUBELET']['NAME'] }}:{{ K8S_IMAGES['KUBELET']['VERSION'] }}
    command:
    - /hyperkube
    - controller-manager
    - --master=http://127.0.0.1:8080
    - --allocate-node-cidrs=true
    - --service-cluster-ip-range={{ K8S_SERVICE_IP_RANGE }}
    - --cluster-cidr={{ K8S_POD_NETWORK }}
    - --cluster-name=kubernetes 
    - --leader-elect=true
    - --service-account-private-key-file=/etc/kubernetes/ssl/apiserver.key
    - --root-ca-file=/etc/kubernetes/ssl/ca.pem
    resources:
      requests:
        cpu: 200m
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10252
      initialDelaySeconds: 15
      timeoutSeconds: 15
    volumeMounts:
    - mountPath: /etc/kubernetes/ssl
      name: ssl-certs-kubernetes
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: ssl-certs-host
      readOnly: true
    - mountPath: /etc/localtime
      name: etc-localtime
      readOnly: true       
  volumes:
  - hostPath:
      path: /etc/kubernetes/ssl
    name: ssl-certs-kubernetes
  - hostPath:
      path: /usr/share/ca-certificates
    name: ssl-certs-host
  - hostPath:
      path: /etc/localtime
    name: etc-localtime      