---
apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  hostNetwork: true
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: "Equal"
      value: "true"
      effect: NoSchedule
    - key: "CriticalAddonsOnly"
      operator: "Exists"       
  containers:
  - name: kube-proxy
    image: {{ REGISTRY_LOCAL }}{{ K8S_IMAGES['KUBE-PROXY']['NAME'] }}:{{ K8S_IMAGES['KUBE-PROXY']['VERSION'] }}
    command:
    - kube-proxy
    - --config=/etc/kubernetes/config/kubeproxy-conf.yaml
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: "etc-ssl-certs"
    - mountPath: /etc/kubernetes/ssl
      name: "etc-kube-ssl"
      readOnly: true
    - mountPath: /etc/kubernetes/config
      name: "etc-kubernetes-config"
      readOnly: true      
    - mountPath: /lib/modules
      name: "lib-modules"
  volumes:
  - name: "etc-ssl-certs"
    hostPath:
      path: "/usr/share/ca-certificates"
  - name: "etc-kube-ssl"
    hostPath:
      path: "/etc/kubernetes/ssl"
  - name: "etc-kubernetes-config"
    hostPath:
      path: "/etc/kubernetes/config"
  - name: "lib-modules"
    hostPath:
      path: "/lib/modules"