- name: mkdir -p /etc/kubernetes/addons/kube-system
  raw: mkdir -p /etc/kubernetes/addons/kube-system

- name: check need rbac-admin.yml
  raw: stat /etc/kubernetes/addons/kube-system/rbac-admin.yml
  register: need_addons_rbac_admin
  ignore_errors: True

- name: template rbac-admin.yml
  template: src=rbac-admin.yml dest=/etc/kubernetes/addons/kube-system/rbac-admin.yml
  when:
  - need_addons_rbac_admin | failed

- name: kubectl create -f rbac-admin.yml
  raw: kubectl create -f /etc/kubernetes/addons/kube-system/rbac-admin.yml
  when: 
  - need_addons_rbac_admin | failed

- name: check need coredns.yml
  raw: stat /etc/kubernetes/addons/kube-system/coredns.yml
  register: need_addons_dns
  ignore_errors: True

- name: template coredns.yml
  template: src=coredns.yml dest=/etc/kubernetes/addons/kube-system/coredns.yml
  when: 
  - need_addons_dns | failed

- name: kubectl create -f coredns.yml
  raw: kubectl create -f /etc/kubernetes/addons/kube-system/coredns.yml
  when: 
  - need_addons_dns | failed  

- name: check need dashboard.yml
  raw: stat /etc/kubernetes/addons/kube-system/dashboard.yml
  register: need_addons_dashboard
  ignore_errors: True

- name: template dashboard.yml
  template: src=dashboard.yml dest=/etc/kubernetes/addons/kube-system/dashboard.yml
  when: 
  - need_addons_dashboard | failed

- name: kubectl create -f dashboard.yml
  raw: kubectl create -f /etc/kubernetes/addons/kube-system/dashboard.yml
  when: 
  - need_addons_dashboard | failed  

- name: check need heapster.yml
  raw: stat /etc/kubernetes/addons/kube-system/heapster.yml
  register: need_addons_heapster
  ignore_errors: True

- name: template heapster.yml
  template: src=heapster.yml dest=/etc/kubernetes/addons/kube-system/heapster.yml
  when: 
  - need_addons_heapster | failed

- name: kubectl create -f heapster.yml
  raw: kubectl create -f /etc/kubernetes/addons/kube-system/heapster.yml
  when: 
  - need_addons_heapster | failed 